---
title: "Decisiones de negocio basadas ITAM  <br> Abril - Junio 2020"
author: "Profesor: David R. Montalván Hernández"
date: "Última actualización `r format(Sys.time(), '%d/%m/%Y - %H:%M:%S')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: vignette
---

# **Bienvenido**

En este curso se tratarán temas relacionados al lenguaje de programación **python** así como su aplicación en las finanzas.

# **Herramientas a utilizar**

Se trabajará principalmente con  [**jupyter notebooks**](https://jupyter.org/) y se explorarán las siguientes librerías:

* [Numpy](https://numpy.org/)

* [Pandas](https://pandas.pydata.org/)

* [Matplotlib](https://matplotlib.org/)

* [Scipy](https://www.scipy.org/)


# **Referencias**

Las referencias serán compartidas por el profesor a tráves de una liga de **one drive**

# **Temario**

|Fecha|Tema|Presentación/datos|Notebook|Ejercicios|Soluciones|
|:-----:|:-----|:------------|:--------|:----------|:--|
|18 abril 2020|01-Introducción a python|Sólo notebook|<a href="./notebooks/lec01-intro.ipynb" download>lec01-intro </a>  |En el notebook|<a href="./soluciones/lec01-intro-soluciones.ipynb" download>lec01-intro-soluciones </a>|
|25 abril 2020|02-Colecciones|Sólo notebook|<a href="./notebooks/lec02-collections.ipynb" download>lec02-colecciones </a>|En el notebook|<a href="./soluciones/lec02-collections-soluciones.ipynb" download>lec02-colecciones-soluciones </a>|
|2 mayo 2020|03 Control de flujo <br> 04 Cíclos|Sólo notebook|<a href="./notebooks/lec03-control-flow.ipynb" download>lec03-control-flow</a> <br> <a href="./notebooks/lec04-loops.ipynb" download>lec04-loops</a>|En el notebook|* <a href="./soluciones/lec03-control-flow-soluciones.ipynb" download>lec03-control-flow-soluciones </a> <br> *<a href="./soluciones/lec04-loops-soluciones.ipynb" download>lec04-loops-soluciones </a>|
|9 mayo 2020|05 Funciones y librerías|Sólo notebook|<a href="./notebooks/lec05-functions.ipynb" download>lec05-functions</a>|En el notebook|<a href="./soluciones/lec05-functions-soluciones.ipynb" download>lec05-functions-soluciones </a>|
|16 mayo 2020|06 Archivos y fechas|<a href="./datos/16_mayo.zip" download>Material clase</a>|<a href="./notebooks/lec06-archivos-fechas.ipynb" download>lec06-archivos-fechas</a>|En el notebook|<a href="./soluciones/lec06-archivos-fechas-soluciones.ipynb" download>lec06-archivos-fechas-soluciones </a>|
|23 mayo 2020|07-Numpy|Sólo notebook|[lec 07 - Numpy](./notebooks/lec07-numpy.ipynb)|En el notebook|[lec 07 - Numpy soluciones](./soluciones/lec07-numpy-soluciones.ipynb)|
|30 mayo 2020|08-Scipy y matplotlib|[Datos bono](./datos/datos_bono.csv)|[lec 08 - Scipy y matplotlib](./notebooks/lec08-scipy-matplotlib.ipynb)|[Proyecto 1 Valuación de bonos](./proyectos/Valuacion_bono.ipynb)|[lec 08- Scipy y matplotlib soluciones](./soluciones/lec08-scipy-matplotlib-soluciones.ipynb)|
|6 junio 2020|09 Programación Funcional|Sólo notebook|[lec 09-prog-fun](./notebooks/lec09-prog-fun.ipynb)|En el notebook|--|

# **Contacto**
Si desean contactarme pueden usar **Teams**.
